apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi:cluster-owner
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/finalizers
  - clusters/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch