apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-cluster  
spec:
  rules:
  - name: create-cluster
    match:
      resources:
        kinds:
        - KubeadmConfigTemplate
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: CREATE
    context:
    - name: meta
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}"
        jmesPath: "metadata" 
    - name: clusterVersion
      variable:
        jmesPath: "meta.annotations.clusterVersion || 'v1.24.3'"
    - name: controlPlaneNodes
      variable:
        jmesPath: "meta.annotations.clusterControlPlaneNodes || `1`"
    - name: workerNodes
      variable:
        jmesPath: "meta.annotations.clusterWorkerNodes || `1`"
    generate:
      apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: "{{request.namespace}}"
      namespace: "{{request.namespace}}"
      data:
        spec:
          clusterNetwork:
            pods:
              cidrBlocks:
              - 192.168.0.0/16
            serviceDomain: cluster.local
            services:
              cidrBlocks:
              - 10.128.0.0/12
          topology:
            version: "{{ clusterVersion }}"
            class: quick-start
            controlPlane:
              metadata: {}
              replicas: "{{ controlPlaneNodes }}"
            variables:
            - name: imageRepository
              value: ""
            - name: etcdImageTag
              value: ""
            - name: coreDNSImageTag
              value: ""
            - name: podSecurityStandard
              value:
                audit: restricted
                enabled: true
                enforce: baseline
                warn: restricted
            workers:
              machineDeployments:
              - class: default-worker
                name: md-0
                replicas: "{{ workerNodes }}"
