apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-cluster  
spec:
  rules:
  - name: create-cluster
    match:
      resources:
        kinds:
        - KubeadmConfigTemplate
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: CREATE
    # context:
    # - name: annotations
    #   apiCall:
    #     urlPath: "/api/v1/namespaces/{{request.namespace}}"
    #     jmesPath: "metadata.annotations"  
    # - name: clusterVersion
    #   variable:
    #     jmesPath: "annotations.clusterVersion || \"v1.24.3\""
    # - name: controlPlaneNodes
    #   variable:
    #     jmesPath: "annotations.clusterControlPlaneNodes || \"1\""
    # - name: workerNodes
    #   variable:
    #     jmesPath: "annotations.clusterWorkerNodes || \"1\""        
    generate:
      apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: "{{request.namespace}}"
      namespace: "{{request.namespace}}"
      data:
        spec:
          clusterNetwork:
            pods:
              cidrBlocks:
              - 192.168.0.0/16
            serviceDomain: cluster.local
            services:
              cidrBlocks:
              - 10.128.0.0/12
          topology:
            # version: "{{ clusterVersion }}"
            version: "v1.24.3"
            class: quick-start
            controlPlane:
              metadata: {}
              # replicas: "{{ to_number(clusterVersion) }}"
              replicas: 1
            variables:
            - name: imageRepository
              value: ""
            - name: etcdImageTag
              value: ""
            - name: coreDNSImageTag
              value: ""
            - name: podSecurityStandard
              value:
                audit: restricted
                enabled: true
                enforce: baseline
                warn: restricted
            workers:
              machineDeployments:
              - class: default-worker
                name: md-0
                # replicas: "{{ to_number(workerNodes) }}"
                replicas: 1
