apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:generate
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingressclasses
  - networkpolicies
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  - resourcequotas
  - limitranges
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusterclasses
  verbs:
  - create
  - update
  - patch
  - delete
  - list
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - dockerclustertemplates
  - dockermachinetemplates
  verbs:
  - create
  - update
  - patch
  - delete
  - list
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanetemplates
  verbs:
  - create
  - update
  - patch
  - delete
  - list
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - kubeadmconfigtemplates
  verbs:
  - create
  - update
  - patch
  - delete
  - list
